repos:
  - repo: local
    hooks:
      - id: test-lifecycle-validation
        name: Test Lifecycle Validation
        entry: python tests/scripts/validate_test_placement.py
        language: system
        files: '^tests/.*\.py$'
        fail_fast: true
        verbose: true

      - id: test-metadata-validation
        name: Test Metadata Validation
        entry: python tests/scripts/validate_test_metadata.py
        language: system
        files: '^tests/.*test_.*\.py$'
        fail_fast: true
